### ISSUE TITLE
Final review

### ISSUE THREAD

**Issue by lschiesser** [lschiesser/ai_programming_task_group27#21]
**This issue is to do last**
- [x] Review code again
- [x] Make sure everything works
- [x] Look at the documentation and comments again. Do they explain everything that our code does?
- [x] Look at the [README.md file](https://github.com/lschiesser/ai_programming_task_group27/blob/functionality-changes/README.md) again and make sure everything is included

**Please indicate your approval by commenting 👍 to this issue**
If all of us indicated their approval one of us will upload the code to our folder in StudIP

**Comment by lschiesser** [comment]
👍

**Comment by lschiesser** [comment]
👍

**Comment by SarahJaehnichen** [comment]
👍🏻

**Comment by ilhwill** [comment]
Everything looks ok when I read over the scripts and readme, but I can't run gui.py. I get the error that I'm missing the PyQt5 module. I have un-installed and re-installed Python and PyQt5, but I'm still getting the error. 

Anyone else experiencing this issue, or just my machine as usual?

**Comment by lschiesser** [comment]
> Everything looks ok when I read over the scripts and readme, but I can't run gui.py. I get the error that I'm missing the PyQt5 module. I have un-installed and re-installed Python and PyQt5, but I'm still getting the error.
> 
> Anyone else experiencing this issue, or just my machine as usual?

I also un- and reinstalled pyqt5 and it works for me, maybe your computer just throws a "you will not work"-fit as it does sometimes 😉

**Comment by ilhwill** [comment]
Well, it worked previously. The other parts besides the GUI seem ok, but someone else will have to test to make sure everything is passing back and forth appropriately --I can only test in piecemeal, but I somehow don't think the work will be graded based on "everything works independently! Just not together...."

**Comment by lschiesser** [comment]
> Well, it worked previously. The other parts besides the GUI seem ok, but someone else will have to test to make sure everything is passing back and forth appropriately --I can only test in piecemeal, but I somehow don't think the work will be graded based on "everything works independently! Just not together...."

Sarah did check on her computer and for her, it worked as well. Berit will test if everything works tonight, so we'll know by then.
